### PR TITLE
ref(deis-dev): change livenessProbe for deis-database

### PR DESCRIPTION
**Pull request by bacongobbler**
to be tested in tandem with deis/postgres#24

### CODE REVIEW

**Comment by mboersma** [comment]
@michelleN and I wondered if `readinessProbe` isn't more appropriate here.

**Comment by helgi** [comment]
A `readiness` probe is more appropriate with a good initial delay. For `liveness` we need to decide if we want to potentially restart the pod if pg reports it self as not running

**Comment by bacongobbler** [comment]
Yeah after tossing around the idea a little bit I think it'd be safer to restart the pod if the database reports itself as down. If minio goes down and the database can no longer back up wal logs, it should become unresponsive, which makes the case for a `readinessProbe` but part of me wonders what kind of issues we could hit in prod with postgres that could make it unresponsive otherwise, which makes me want to lean towards the "kill if unresponsive" approach for now. Once we start getting more data/usage from actual clusters then we can tune these settings as we see fit.

**Comment by helgi** [comment]
The readiness probe is more about not letting anything think it is up and running before it is ready :) thus the delay. But I hear ya

**Comment by mboersma** [comment]
I'm fine with merging the `livenessProbe`--the distinction is arguable here and I agree that all these values are likely to be refined post-beta.

**Pull request merged**
