### PR TITLE
bug(labels): create daemonset with pod selectors

### PR DESCRIPTION
**Pull request by slack**

### CODE REVIEW

**Comment by slack** [comment]
I need to do this against `workflow-dev` as well, juan momento.

**Comment by slack** [comment]
deis-logger needs an update as well?

**Comment by bacongobbler** [comment]
manually tested; works. the deis-workflow-e2e pod is no longer destroyed.

**Comment by bacongobbler** [comment]
Wouldn't hurt to do so

**Comment by vdice** [comment]
Also tested manually -- tests are now running (`workflow-dev-e2e` not deleted by daemonset)

**Pull request merged**
