### PR TITLE
feat(minio): Add option to use hostPath for minio storage

### PR DESCRIPTION
**Pull request by tmc**
This adds an option to minio to set up a hostPath volume. Running deis in minikube is a use case.

### CODE REVIEW

**Comment by helgi** [comment]
You'll want to do those changes against `workflow-dev`. That's the chart we use as the basis for releases

**Comment by bacongobbler** [comment]
This will only work with single-node clusters where there is only one worker node available. As long as we're abundantly clear about that in the docs I'm OK with this.

**Comment by rimusz** [comment]
the option of `nodeSelector` should be there as well if the k8s cluster is not the single-node one.

**Comment by bacongobbler** [comment]
we've stopped development on helm-classic. Please re-open another PR on deis/minio against that chart. Thanks!

**Pull request closed without merging**
