### PR TITLE
feat(registry): add proxy daemon set make registry available on local host

### PR DESCRIPTION
**Pull request by kmala**

### CODE REVIEW

**Comment by slack** [comment]
Testing the stack of stuff:
- controller: `quay.io/jhansen/controller:git-71843f5`
- builder: `jhansen/builder:git-1404a97`
- dockerbuilder: `jhansen/dockerbuilder:git-b23f272`

All the pieces seem connected, but having an issue with registry pushing to minio and receiving an i/o timeout + retry with docker push:

```
[ DELETED STUFFS ]
remote: ":"Pushing","progressDetail":{"current":6761472,"total":4878745},"progress":"[==================================================\u003e] 6.761 MB","id":"790f7b6a5fee"}
remote: ":"Retrying in 20 seconds","progressDetail":{},"id":"30f465440fa6"}
remote: ":"Retrying in 20 seconds","progressDetail":{},"id":"d3b579b4d36f"}
[ DELETED STUFFS ]
remote: ":"Pushing","progressDetail":{"current":6745700,"total":4878745},"progress":"[==================================================\u003e] 6.746 MB","id":"790f7b6a5fee"}
remote: ":"Pushing","progressDetail":{"current":6761472,"total":4878745},"progress":"[==================================================\u003e] 6.761 MB","id":"790f7b6a5fee"}
remote: etail":{"message":"dial tcp 10.3.0.224:9000: i/o timeout"},"error":"dial tcp 10.3.0.224:9000: i/o timeout"}
size of streamed logs 221689
Waiting for the deis/dockerbuild-zeroed-bagpiper-2eb1c4f3-da6261e2 pod to end. Checking every 100ms for 15m0s
Done
Checking for builder pod exit code
remote: 2016/07/12 00:52:05 Error running git receive hook [Build pod exited with code 1, stopping build.]
```

No useful output from the proxy container, so I suspect the proxy but I'm not ready to attribute ownership of this bug to the proxy (yet). 👯

**Comment by kmala** [comment]
It seems to be working fine for me with minio....i see `dial tcp 10.3.0.224:9000` why is it trying to ping 10.3.0.224 shouldn't it be localhost?

**Comment by slack** [comment]
The error message is returned from the registry trying to talk to minio:
- Docker push -> proxy -> registry -> minio

Was thinking about the problem this morning and I'm wondering if the failure to push was the same thing @krancour was seeing with Docker 1.11.0

Yep, seeing the same symptoms from (https://github.com/deis/registry/issues/60) and since the registry is now _always_ colocated thanks to the proxy I'm getting the push, timeout, retry that Kent saw.

**Comment by slack** [comment]
New cluster, new install:

```
w:tirefire k:tirefire
example-dockerfile-http [master]$ curl owlish-kingfish.tirefire.slack.io
Powered by Deis
```

 LGTM 👯

**Comment by slack** [comment]
We will certainly need to release note this. Can't think of a scenario where this would be a breaking change for 2.1 folks.

**Pull request merged**
