### PR TITLE
feat(deis-logger): use git based tag for logger

### PR DESCRIPTION
**Pull request by sgoings**
Will be automatically updated by Jenkins

### CODE REVIEW

**Comment by sgoings** [comment]
/cc @jchauncey 

Do we want to do this or do we want to split logger into:

deis-logger (reference v2-beta)
deis-logger-dev (reference git sha)

**Comment by jchauncey** [comment]
So I wonder if there should be a deis-logger-dev chart. But some of this hinges on if we are going to fold deis-logger into the deis chart this week.

**Comment by sgoings** [comment]
So we have two options:
- if we require daemonset support in the deis beta release we're going to have to use something other than GKE to run automated tests
- if we don't require daemonset support, then the charts will have to be separated into the deis-logger/deis-logger-dev chart

@slack can you chime in on the DaemonSet decision?

**Comment by rimusz** [comment]
I would stay away from daemonset support till v1.2 is released and GKE supports it

**Comment by slack** [comment]
The release of Deis v2.0.0 requires DaemonSets for logs to function, so we are pretty much defacto requiring DS as a result.

My current thinking (not a dictation!):
1. We should probably merge the charts so day to day development starts to put coverage on logging functionality.
2. We should templatize the charts to disable logging on GKE so e2e tests aren't entirely impacted.
3. We should look at what we will need to do to support DaemonSets on a 1.2 cluster. When the API is promoted we'll possibly need helm to handle v1.1 and v1.2 k8s modes.

**Comment by rimusz** [comment]
+1

**Comment by sgoings** [comment]
I'm waiting to update + merge this until deis e2e tests are green again.

**Comment by jchauncey** [comment]
closing this now that logger is part of `workflow`

**Pull request closed without merging**
