### PR TITLE
fix(logger): Update env vars for finding syslog port and host

### PR DESCRIPTION
**Pull request by jchauncey**
This is in response to changes from @krancour

### CODE REVIEW

**Comment by krancour** [comment]
This is much nicer since it doesn't include the port number in the env var names. :+1:

**Comment by krancour** [comment]
This should be merged _before_ #104

**Comment by krancour** [comment]
This should be combined with #107.

**Comment by jchauncey** [comment]
if you want to put this change in your PR I can just delete this one

**Comment by krancour** [comment]
@jchauncey done.  See updates to #107

**Pull request closed without merging**
