### PR TITLE
feat(deis-ui): add deis-ui chart

### PR DESCRIPTION
**Pull request by bacongobbler**
See https://github.com/jumbojett/deis-ui

I've set up an automated job at https://quay.io/repository/fishworks/deis-ui which builds off pushes from https://github.com/fishworks/deis-ui on master. We'll have to eventually get @jumbojett's repository automatically deploying images from master so we don't need to rely on a third party (me) to keep my mirror up to date :)

To use:

```
$ helm install deis-dev
$ helm install deis-ui
```

Then hit www.$ROUTER_PUBLIC_IP.xip.io to view the web UI.

### CODE REVIEW

**Comment by mboersma** [comment]
I installed this but haven't been able to get the pod to escape from `Error` or `CrashLoopBackoff` status. Here is the pod log:

```
$ kubectl --namespace=deis logs -f deis-ui-hy5a8
Running "serve:dist" (serve) task

Running "clean:dist" (clean) task
Cleaning .tmp...OK
Cleaning dist/404.html...OK
Cleaning dist/favicon.ico...OK
Cleaning dist/fonts...OK
Cleaning dist/images...OK
Cleaning dist/index.html...OK
Cleaning dist/robots.txt...OK
Cleaning dist/scripts...OK
Cleaning dist/styles...OK
Cleaning dist/views...OK

Running "ngconstant:production" (ngconstant) task
Creating module config at .tmp/scripts/config.js...OK

Running "wiredep:app" (wiredep) task

modernizr was not injected in your file.
Please go take a look in "/app/bower_components/modernizr" for the file you need, then manually include it in your file.

Running "useminPrepare:html" (useminPrepare) task
Configuration changed for concat, uglify, cssmin

Running "concurrent:dist" (concurrent) task
>> Warning: There are more tasks than your concurrency limit. After this limit
>> is reached no further tasks will be run until the current tasks are
>> completed. You can adjust the limit in the concurrent task options
    Warning:  Use --force to continue.

        Aborted due to warnings.


Execution Time (2016-02-05 22:00:38 UTC)
wiredep:app      231ms  ▇▇▇▇ 8%
concurrent:dist   2.6s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 88%
Total 3s
$ kubectl --namespace=deis get po
NAME                        READY     STATUS             RESTARTS   AGE
deis-builder-o7ern          1/1       Running            1          37m
deis-database-9ximk         1/1       Running            0          37m
deis-etcd-1-0ccd7           1/1       Running            0          37m
deis-etcd-1-6zkji           1/1       Running            1          37m
deis-etcd-1-pok09           1/1       Running            1          37m
deis-etcd-discovery-u1ffs   1/1       Running            0          37m
deis-minio-68vvs            1/1       Running            0          37m
deis-registry-m27mi         1/1       Running            0          37m
deis-router-030ff           1/1       Running            0          37m
deis-ui-hy5a8               0/1       CrashLoopBackOff   5          6m
deis-workflow-cb3tl         1/1       Running            0          37m
```

**Comment by bacongobbler** [comment]
I've been having troubles getting it to boot as well. I'm going to tinker around with it some more. Until then I'll be hosting it at https://github.com/fishworks/charts so people can play around with it there :)

**Comment by jumbojett** [comment]
> We'll have to eventually get @jumbojett's repository automatically deploying images from master

@bacongobbler I'd be more than happy to set this up. How do I start?

**Comment by bacongobbler** [comment]
You can do this using one of two ways:
1. create a user on DockerHub, then create a repository for deis-ui. Once that's set up, create a hook that will build a Docker image on every push. [link to the docs](https://docs.docker.com/docker-hub/builds/)
2. Same thing as above, but for quay.io. [link](http://blog.devtable.com/2014/03/link-your-quayio-repositories-to-github.html)

I'll toss an issue onto deis-ui so we can track this :)

**Pull request closed without merging**
