### PR TITLE
fix(deis-dev/tpl/deis-builder-rc.yaml): make the objectstore-creds secret read-only

### PR DESCRIPTION
**Pull request by arschles**
As far as I know, builder does not write to this volume, nor should it.

@smothiki thoughts?

### CODE REVIEW

**Comment by smothiki** [comment]
Code LGTM . Yeah builder just reads the secret

**Comment by jchauncey** [comment]
This needs a rebase but looks like we should have this change. Can we merge this?

**Comment by arschles** [comment]
Not sure if we can merge, I haven't tested in a long time. Moving to RC1 with the intention of testing there

**Comment by arschles** [comment]
Pushing this to v2, as testing is blocked by https://github.com/deis/builder/issues/351

**Pull request merged**
