### PR TITLE
fix(deis-dev/manifests/deis-minio-service.yaml): make the minio service listen on port 80

### LINKED ISSUE #138: Make the deis-dev/minio service serve http on port 80
Ref deis/deis#4853
Ref deis/deis#4809

### PR DESCRIPTION
**Pull request by arschles**
Fixes #138
Ref deis/deis#4853

cc/ @smothiki @kmala

### CODE REVIEW

**Comment by arschles** [comment]
@bacongobbler were you able to get a cluster to successfully run with this change? In my testing the database went into `CrashLoopBackoff`

**Comment by arschles** [comment]
I think these are relevant logs here are the relevant logs from the database pod:

``` console
/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/002_create_bucket.sh
Traceback (most recent call last):
  File "/bin/create_bucket", line 21, in <module>
    conn.meta.client.head_bucket(Bucket=bucket_name)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 231, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 478, in _make_api_call
    operation_model, request_dict)
  File "/usr/local/lib/python2.7/dist-packages/botocore/endpoint.py", line 117, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/lib/python2.7/dist-packages/botocore/endpoint.py", line 146, in _send_request
    success_response, exception):
  File "/usr/local/lib/python2.7/dist-packages/botocore/endpoint.py", line 219, in _needs_retry
    caught_exception=caught_exception)
  File "/usr/local/lib/python2.7/dist-packages/botocore/hooks.py", line 226, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/hooks.py", line 209, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 250, in __call__
    caught_exception)
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 273, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 313, in __call__
    caught_exception)
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 222, in __call__
    return self._check_caught_exception(attempt_number, caught_exception)
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 355, in _check_caught_exception
    raise caught_exception
botocore.exceptions.ConnectionClosedError: Connection was closed before we received a valid response from endpoint URL: "http://10.171.248.179:80/dbwal".
```

**Comment by bacongobbler** [comment]
> botocore.exceptions.ConnectionClosedError: Connection was closed before we received a valid response from endpoint URL: "http://10.171.248.179:80/dbwal".

That's an interesting error. The database saw the service port change but it's not able to receive a response from minio?

**Comment by arschles** [comment]
apparently so, however, minio does seem to get requests from the database after the bucket create failure happens. those requests fail, of course, because the bucket doesn't exist :(

**Comment by bacongobbler** [comment]
Interesting. I'll revoke my LGTM until I get to the bottom of this.

**Comment by arschles** [comment]
Sounds good, thanks @bacongobbler

**Comment by bacongobbler** [comment]
I came to the same conclusion, but I do not know why we cannot connect to minio. Perhaps this is the same issue as to why we cannot get minio working as a standalone docker image for https://github.com/deis/postgres/issues/41?

In other words, connecting differently than how minio is configured: https://github.com/deis/minio/blob/addf8e6225cab434b546795a532284fa8db16f73/boot.go#L131

**Comment by bacongobbler** [comment]
Perhaps we should punt on this one for now until we figure out what is causing this issue? Seems like a nitpick more than a significant change, at least for the time being.

**Comment by arschles** [comment]
I'm good with that. However, this is a requirement to close https://github.com/deis/deis/issues/4853, which is also on beta. @slack thoughts on moving https://github.com/deis/deis/issues/4853 to RC1?

**Comment by slack** [comment]
If we expect folks to want to upgrade in-place from Beta to RC or Release then we should do this before beta.

I know these changes (deis/deis#4853 and deis/deis#4952) are introducing instability in the 11th hour. I believe that even while late, it puts on a better footing for post beta activities. If there is consensus that it isn't worth it, we can move these issues to RC.

**Comment by arschles** [comment]
@slack ah, yea, I forgot about that small (!) point

**Comment by slack** [comment]
Just to clarify my comment a bit further. There certainly no love lost if we _do_ move these to RC! I see both sides on this one.

**Comment by bacongobbler** [comment]
So here was the uncaught error from minio that I've since fixed with https://github.com/deis/postgres/pull/61:

```
Traceback (most recent call last):
  File "/bin/create_bucket", line 22, in <module>
    conn.meta.client.head_bucket(Bucket=bucket_name)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 231, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 489, in _make_api_call
    raise ClientError(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadBucket operation: Forbidden
```

And the issue is (bum-bada-bum-bummm!) boto3! Who would've guessed that the port number is significant to boto3?!

```
root@deis-database-59l70:/# cat /etc/wal-e.d/env/S3_URL 
http://10.247.184.60:80
root@deis-database-59l70:/# envdir /etc/wal-e.d/env create_bucket 
Traceback (most recent call last):
  File "/bin/create_bucket", line 21, in <module>
    conn.meta.client.head_bucket(Bucket=bucket_name)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 231, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 489, in _make_api_call
    raise ClientError(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadBucket operation: Forbidden
```

Changing S3_URL just a bit...

```
root@deis-database-59l70:/# cat /etc/wal-e.d/env/S3_URL 
http://10.247.184.60
root@deis-database-59l70:/# envdir /etc/wal-e.d/env create_bucket 
root@deis-database-59l70:/# echo $?
0
```

God I hate boto3 some days.

**Comment by bacongobbler** [comment]
Still some more boto3/botocore bugs with deis/postgres#62... I know they specifically call out port 80 and port 443 in their code in a few places.

```
./docker-entrypoint.sh: running /docker-entrypoint-initdb.d/003_restore_from_backup.sh
Rebooting postgres to enable archive mode
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
waiting for server to shut down....LOG:  database system is shut down
 done
server stopped
waiting for server to start....LOG:  database system was shut down at 2016-03-05 01:56:17 UTC
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
 done
server started
wal_e.main   CRITICAL MSG: An unprocessed exception has avoided all error handling
        DETAIL: Traceback (most recent call last):
          File "/usr/local/lib/python2.7/dist-packages/wal_e/cmd.py", line 532, in main
            backup_cxt.backup_list(query=args.QUERY, detail=args.detail)
          File "/usr/local/lib/python2.7/dist-packages/wal_e/operator/backup.py", line 66, in backup_list
            for bi in bl_iter:
          File "/usr/local/lib/python2.7/dist-packages/wal_e/worker/base.py", line 153, in __iter__
            for key in self._backup_list(self.layout.basebackups()):
          File "/usr/local/lib/python2.7/dist-packages/boto3/resources/collection.py", line 83, in __iter__
            for page in self.pages():
          File "/usr/local/lib/python2.7/dist-packages/boto3/resources/collection.py", line 166, in pages
            for page in pages:
          File "/usr/local/lib/python2.7/dist-packages/botocore/paginate.py", line 99, in __iter__
            response = self._make_request(current_kwargs)
          File "/usr/local/lib/python2.7/dist-packages/botocore/paginate.py", line 171, in _make_request
            return self._method(**current_kwargs)
          File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 228, in _api_call
            return self._make_api_call(operation_name, kwargs)
          File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 486, in _make_api_call
            raise ClientError(parsed_response, operation_name)
        ClientError: An error occurred (SignatureDoesNotMatch) when calling the ListObjects operation: The request signature we calculated does not match the signature you provided.

        STRUCTURED: time=2016-03-05T01:56:19.502750-00 pid=860
No backups found. Performing an initial backup...
wal_e.main   INFO     MSG: starting WAL-E
        DETAIL: The subcommand is "backup-push".
        STRUCTURED: time=2016-03-05T01:56:19.649489-00 pid=867
wal_e.operator.backup INFO     MSG: start upload postgres version metadata
        DETAIL: Uploading to s3://dbwal/basebackups_005/base_000000010000000000000002_00000040/extended_version.txt.
        STRUCTURED: time=2016-03-05T01:56:19.955556-00 pid=867
wal_e.blobstore.s3.calling_format INFO     MSG: connecting to S3 with WALE_S3_ENDPOINT (http://10.247.184.60:80)
        STRUCTURED: time=2016-03-05T01:56:19.955980-00 pid=867
botocore.credentials INFO     Found credentials in environment variables.
boto3.resources.action INFO     Calling s3:put_object with {'Body': <cStringIO.StringI object at 0x7f84fd4f2828>, u'Bucket': 'dbwal', 'Key': 'basebackups_005/base_000000010000000000000002_00000040/extended_version.txt'}
botocore.vendored.requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): 10.247.184.60
wal_e.operator.backup WARNING  MSG: blocking on sending WAL segments
        DETAIL: The backup was not completed successfully, but we have to wait anyway.  See README: TODO about pg_cancel_backup
        STRUCTURED: time=2016-03-05T01:56:19.993189-00 pid=867
NOTICE:  WAL archiving is not enabled; you must ensure that all required WAL segments are copied through other means to complete the backup
wal_e.main   CRITICAL MSG: An unprocessed exception has avoided all error handling
        DETAIL: Traceback (most recent call last):
          File "/usr/local/lib/python2.7/dist-packages/wal_e/cmd.py", line 557, in main
            pool_size=args.pool_size)
          File "/usr/local/lib/python2.7/dist-packages/wal_e/operator/backup.py", line 197, in database_backup
            **kwargs)
          File "/usr/local/lib/python2.7/dist-packages/wal_e/operator/backup.py", line 487, in _upload_pg_cluster_dir
            content_encoding='text/plain')
          File "/usr/local/lib/python2.7/dist-packages/wal_e/worker/worker_util.py", line 13, in uri_put_file
            content_encoding=content_encoding)
          File "/usr/local/lib/python2.7/dist-packages/wal_e/blobstore/s3/s3_util.py", line 51, in uri_put_file
            k = bucket.put_object(Key=url_tup.path.lstrip('/'), Body=fp)
          File "/usr/local/lib/python2.7/dist-packages/boto3/resources/factory.py", line 481, in do_action
            response = action(self, *args, **kwargs)
          File "/usr/local/lib/python2.7/dist-packages/boto3/resources/action.py", line 83, in __call__
            response = getattr(parent.meta.client, operation_name)(**params)
          File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 228, in _api_call
            return self._make_api_call(operation_name, kwargs)
          File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 486, in _make_api_call
            raise ClientError(parsed_response, operation_name)
        ClientError: An error occurred (SignatureDoesNotMatch) when calling the PutObject operation: The request signature we calculated does not match the signature you provided.

        STRUCTURED: time=2016-03-05T01:56:20.042688-00 pid=867
```

**Comment by arschles** [comment]
@bacongobbler since deis/postgres#61 has been merged, is this now working?

**Comment by bacongobbler** [comment]
This is still not working due to the above errors. I have not been able to determine what causes this issue to occur once you change the port number.

**Comment by arschles** [comment]
k, thanks for letting me know. gonna hold off on this still

**Comment by jchauncey** [comment]
Can we close this PR

**Comment by jchauncey** [comment]
@arschles @smothiki  can we close this?

**Comment by bacongobbler** [comment]
yes. let's close for now and open a ticket on deis/postgres, then revisit later once we get that working.

**Pull request closed without merging**
