### PR TITLE
ref(etcd): remove etcd component as it is no longer used anywhere

### PR DESCRIPTION
**Pull request by helgi**

### CODE REVIEW

**Comment by helgi** [comment]
king

**Comment by carmstrong** [comment]
ron ron

**Comment by arschles** [comment]
@helgi :ship: :it:

**Comment by mboersma** [comment]
Holy cow it works:

``` console
$ kubectl --namespace=deis get pods
NAME                  READY     STATUS    RESTARTS   AGE
deis-builder-c7jq8    1/1       Running   0          6m
deis-database-gmdvb   1/1       Running   0          6m
deis-minio-y9aze      1/1       Running   0          6m
deis-registry-dqqs4   1/1       Running   0          6m
deis-router-8s0dh     1/1       Running   0          6m
deis-workflow-a1ntk   1/1       Running   0          6m
```

I ran the e2e tests and did some manual `git push` testing.

**Comment by ohohoreilly** [comment]
+1

**Pull request merged**
