### PR TITLE
chore(deis-tests-parallel): Back down the number of concurrent test processes

### PR DESCRIPTION
**Pull request by jchauncey**

### CODE REVIEW

**Comment by vdice** [comment]
@jchauncey It could be handy as we go thru the trial-and-error process of tuning the parallel test runs if this particular value was configurable via an env var? Then we can have a default and be able to config on the fly (via the Jenkins job.)

Aside from that (we can create a ticket if it sounds helpful), this LGTM.

**Comment by jchauncey** [comment]
yeah you know how we could do that?

**Comment by vdice** [comment]
Not immediately, but figure there are examples of other component manifests that use env vars in a similar fashion.

**Comment by jchauncey** [comment]
lets go ahead and back it down so i can watch the parallel runs today.

**Pull request merged**
